### ISSUE TITLE
Accuracy error

### ISSUE THREAD

**Issue by Merichbier** [doughtmw/ArUcoDetectionHoloLens-Unity#27]
Hi, 

I just build your repo and tested the ArUCo detection. Works fine, but I always get some offset between the cube and the marker.
Is there any calibration that need to be done ?

PS : the screenshot is not really relevant because the MRC doesn't align Holograms correctly with the world but still wanted to share it.. 
(https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/mixed-reality-capture-for-developers)
![20201216_135122_HoloLens](https://user-images.githubusercontent.com/9365869/102363090-615c4700-3fb5-11eb-8b72-21ba2945b97a.jpg)

**Comment by doughtmw** [comment]
Hi @Merichbier, I'm familiar with this offset. It is caused by the difference in the relative coordinate systems of a user's eyes and the tracking camera. There are a few ways to perform a calibration to reduce this error - most of them rely on manual interaction. [Here](https://arxiv.org/pdf/1709.04299.pdf) is a solid review paper that gives an overview of some of these methods. I'm also working on my own method for calibration which I will *hopefully* release within the next several months.

**Comment by Merichbier** [comment]
@doughtmw thanks for the answer and your work :)

**Comment by doughtmw** [comment]
Hi @Merichbier, in the most recent commit (1551c8edd1f048c5d9b3b6a2d413c31c76cb43b9) I updated the sample to allow for user-defined camera calibration parameters in Unity which should improve the accuracy of tracking with your headset. Previously the sample was using parameters that I calculated for my own personal headset - but the optimal parameters will differ between devices.

**Comment by nocardio** [comment]
Hi @doughtmw, I am sorry to interrupt the conversation. Did you get the camera parameter after performing calibration using usual chessboard pattern (with the stationary hololens position)? Or did you performed the manual cube calibration described in the Qian's paper [above](https://arxiv.org/pdf/1709.04299.pdf)?

Thank you .
