### ISSUE TITLE
Error when bluilding HoloLensForCV sample

### ISSUE THREAD

**Issue by roalchaq** [doughtmw/ArUcoDetectionHoloLens-Unity#5]
Hi @doughtmw 

Thank you for sharing your project.

When I first open the HoloLensForCV sample, I noticed that there are two projects in the solution that say "load failed": Debugging and Io. If I just ignore then and proceed trying to install the  OpenCV.UWP.411 nugget package, I don't find any with this name, instead I find OpenCV.HoloLens v3411.0.0 (highlighted as missing from the solution) and OpenCV.Windows v411.0.0. I then just click "Restore" under the "Manage Nuget Packages" menu. When I try to build the project (x86, Debug or Release) I got an error that says:

* The imported project file "C:\Program Fules (x86)\Windows Kits\10\bin\10.0.17134.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets" could not be loaded. Root element is missing.

Have you come across this issue?

Best,

Rodrigo

**Comment by doughtmw** [comment]
Hi @roalchaq, I've updated the README file to reflect some of the recent changes I've made to the project to support the HoloLens 2. After cloning the repo, be sure to install the submodules using git by calling `git submodule update --init` from the root of the repo. The project now uses the OpenCV.HoloLens.3411 NuGet package, which is made available in the linked submodule (rather than the OpenCV.UWP.411 pack). Let me know if this resolves the issues!

**Comment by roalchaq** [comment]
Found the issue, Debugging and Io projects were not loading because their TargetPlatformVersion tags declare a different version than the one needed: 10.0.17134.0 instead of 10.0.17763.0. If you change them as indicated here:

https://stackoverflow.com/questions/42152614/microsoft-windows-ui-xaml-common-targets-was-not-found-in-xamarin-project

the project builds just fine. Thank you for your help.
